baseURL = "/"
languageCode = "en-us"
title = "Developer Pacenotes"
theme = "future-imperfect"
paginate = 5
publishDir = "docs"
disqusShortname = "developer-pacenotes-com"
preserveTaxonomyNames = true

[params]
	author = "Dimitar Trendafilov"
	subtitle = "Flat over problems. Don't cut!"
	navbarTitle = "Developer Pacenotes"
	socialAppearAtBottom = true
	socialAppearAtTop = false
	googleAnalytics = "UA-109980000-1"
	loadFavicon = true

[params.intro]
	# header = "Developer Pacenotes"
	paragraph = "Flat over problems.<br/><b>Don't cut!</b>"

[params.postAmount]
	sidebar = 3

# Sets the menu items in the navigation ba Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 2


[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[social]
	twitter = "DimitarNT"
	github = "dimitarcl"
	email = "dimitar@coherent-labs.com"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"
